### PR TITLE
Remove commented code from json_helper.cpp

### PR DESCRIPTION
**Pull request by luator**
[//]: # "Thanks for your contribution.  To make life of the reviewers easier,"
[//]: # "please give this pull request a meaningful title and provide the"
[//]: # "requested information below."

## Description

The tabs in this commented code was causing some trouble for auto-formatting.  If I understood correctly, this has been copied to the header, so I thought it might be best to simply remove it from the cpp file.  Please let me know in case it is still needed there for some reason.

Another question would be if there actually needs to be cpp at all if it is header-only, so maybe I could go a step further and remove the whole file?

## How I Tested
Build the PAM_MUJOCO workspace.

## I fulfilled the following requirements

[//]: # "Please make sure you followed these steps before requesting a review."
[//]: # "Check the boxes in the list below, when done."

- [x] All new code is formatted according to our style guide (for C++ run clang-format, for Python, run flake8 and fix all warnings).
- [x] All new functions/classes are documented and existing documentation is updated according to changes.
- [x] No commented code from testing/debugging is kept (unless there is a good reason to keep it).

### CODE REVIEW

**Comment by luator** [comment]
@vincentberenz @dtrb What do you think about this?  Would there be any problem if I completely get rid of the cpp file and turn it into a header-only library?

**Comment by vincentberenz** [comment]
@luator all good to me !

**Comment by dtrb** [comment]
Jep, seems reasonable.

**Review by dtrb — APPROVED** [review]
lgtm

**Comment by luator** [comment]
I now removed the cpp file completely and adjusted the CMakeLists.txt accordingly.  Tested by building the PAM_MUJOCO workspace.

**Review by vincentberenz — APPROVED** [review]

**Pull request merged**
